import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function TopNavigationBar() {
  return (
    <nav className="flex w-full items-center justify-between text-xl p-4 font-semibold border-b">
      <Link href="/questions">Problems</Link>
      <div>Sign in</div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-sans flex flex-col gap-4`}>
        <TopNavigationBar/>
        {children}
      </body>
    </html>
  );
}
